<a href="https://colab.research.google.com/github/sofyitahm/SKRIPSI/blob/main/FIKZ_PERFORMA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install scikit-learn==1.2.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 54.0 MB/s eta 0:00:00


# DATA

In [213]:
import pandas as pd
import numpy as np

In [214]:
#import data
dfbaru1=pd.DataFrame
url = 'https://raw.githubusercontent.com/sofyitahm/SKRIPSI/main/performa.csv'
dfbaru1 = pd.read_csv(url)
dfbaru1 = dfbaru1.astype({'ulasan' : 'string'})

In [215]:
dfbaru1.head()

ulasan  label
0  Tolong di perbaiki lagi aplikasi ini,sering lo...      0
1  Setelah update kenapa jadi susah buat cek tike...      0
2  Setelah update saya tidak bisa menggunakan pro...      0
3                               saat login lamaaAAAA      0
4  Fitur lebih banyak dan tampilan lebih bagus ta...      1

# RESAMPLING

In [216]:
!pip install imbalanced-learn

In [217]:
from imblearn.over_sampling import RandomOverSampler

x = dfbaru1['ulasan']
y = dfbaru1['label']

# Reshape x untuk mengubah bentuk array, karena x adalah 1 dimensi
x_reshaped = np.array(x).reshape(-1, 1)

ros = RandomOverSampler(random_state=42)
x_sm, y_sm= ros.fit_resample(x_reshaped, y)

print(y_sm.value_counts())

0    323
1    323
Name: label, dtype: int64


# SPLIT

In [218]:
## lihat data awal
x_sm.shape

(646, 1)

In [219]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_sm, y_sm, test_size=0.2, stratify=y_sm, random_state=42)
#statify=selang-seling target
#random state=mau shuffle tapi yg reproducible

In [220]:
##lihat pembagian data
X_train.shape, X_test.shape

((516, 1), (130, 1))

In [221]:
y_train.value_counts(), y_test.value_counts()

(0    258
 1    258
 Name: label, dtype: int64,
 0    65
 1    65
 Name: label, dtype: int64)

In [222]:
y_test

282    0
270    0
369    1
13     1
438    1
      ..
310    0
619    1
323    0
412    1
127    0
Name: label, Length: 130, dtype: int64

# DATA LATIH

In [223]:
y_train=y_train.reset_index(drop=True)

In [224]:
dflatih=pd.DataFrame()
dflatih['kalimat']=X_train.flatten()
dflatih['label']=y_train
dflatih.head()

kalimat  label
0  Bagus sih ada beberapa bagian menu yg bukanya ...      0
1  Lemotnya minta ampun.. Bagaimana mau melayani ...      0
2                                              Lemot      0
3  Mohon maaf setelah update akses menjadi lebih ...      0
4                     Lemot sekali kapan normal lagi      0

## PREPROCESSING

### NORMALISASI

In [225]:
import requests

# Fungsi untuk normalisasi kata
def word_normalize(document):
    url = "https://api.prosa.ai/v2/text/normalizer"
    api_key = "eyJhbGciOiJSUzI1NiIsImtpZCI6Ik5XSTBNemRsTXprdE5tSmtNaTAwTTJZMkxXSTNaamN0T1dVMU5URmxObVF4Wm1KaSIsInR5cCI6IkpXVCJ9.eyJhcHBsaWNhdGlvbl9pZCI6Mjk2OTI3LCJsaWNlbnNlX2tleSI6IjU0MjJhODRkLWVmZGYtNDhiNC1iMDQ4LWM5N2I4OGU2MDYzMSIsInVuaXF1ZV9rZXkiOiI0YTY3YWVlMy1lMGNiLTRiMzUtOTI4Ni0xMjlhMWE2NjNkMjEiLCJwcm9kdWN0X2lkIjoxMCwiYXVkIjoiYXBpLXNlcnZpY2UiLCJzdWIiOiJkMmZmYzRhMy0wYzI2LTRjNWEtYjRiMS05NDE2NjAyMmJlMDEiLCJpc3MiOiJjb25zb2xlIiwiaWF0IjoxNzAxOTU0NjA1fQ.lJNpppK8iwSc8rH8lAPEHLxEAQW5PQGJrwYmzuAu1U0EmyZzL19dCfROqTAPViBdjecNhvPaV2wOQhJixgAgJjmtZFcdPRI0nUIxBW6AmR52fJW31bOvxcZO61zEk5LbASgBGLRs4--2yoYa3wpfDuNvV88o5slANh6GGgAADzYwnpxI4jM5quHnhNVBmzIMWNcmWOe-TF-hD6zZFX5ijGBLawFCuMjnW_dDedOJxSSPRKY_BoJLGjP-IbOkgOVuZ5F-LO1tJg_Ap7YoY4BajKSPDKuYbj56i9Wa_lj9ZlCYfybvcmbKgczHcziMm7mu9gngYfwxty5CCPquQK8wyA"  # Gantilah dengan kunci API yang diberikan kepada Anda

    # Request header
    headers = {
        "Content-Type": "application/json",
        "x-API-Key": api_key
    }

    # Request body
    payload = {
        "text": document
    }

    # request post
    response = requests.post(url, headers=headers, json=payload)

    # cek jika berhasil
    if response.status_code == 200:
        # Mengembalikan teks hasil normalisasi
        return response.json().get('normalized_text', '')
    else:
        # memberikan hasil status code dan alasan text tidak berhasil
        return response.status_code, response.text

# Menambahkan kolom baru 'text_baru' ke dfcoba sebagai kolom
dflatih['kalimat']=dflatih['kalimat'].apply(word_normalize)

print(dflatih['kalimat'].head(6))

0    Bagus sih ada beberapa bagian menu yang bukann...
1    Lemotnya minta ampun. Bagaimana mau melayani p...
2                                                Lemot
3    Mohon maaf setelah memperbarui akses menjadi l...
4                       Lemot sekali kapan normal lagi
5    Mau naik kereta api pesanannya makin mudah, ap...
Name: kalimat, dtype: object


### CASE FOLDING

In [226]:
dflatih['kalimat'] = dflatih['kalimat'].str.lower()

print('Hasil case folding : \n')
print(dflatih['kalimat'].head(6))

Hasil case folding : 

0    bagus sih ada beberapa bagian menu yang bukann...
1    lemotnya minta ampun. bagaimana mau melayani p...
2                                                lemot
3    mohon maaf setelah memperbarui akses menjadi l...
4                       lemot sekali kapan normal lagi
5    mau naik kereta api pesanannya makin mudah, ap...
Name: kalimat, dtype: object


### CLEANING

In [227]:
import string
import re #regex library
import nltk

# import word_tokenize & FreqDist from NLTK
from nltk.tokenize import word_tokenize


In [232]:
dflatih = dflatih.dropna(subset=['kalimat'])

In [233]:
# ------ cleaning ---------
nltk.download('punkt')

# hapus tab, enter, back slice dll
def remove_tweet_special(text):
    # remove tab, baris baru, back slice
    text = text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")
    # remove non ASCII (emoticon, chinese word, .etc)//semua string di encode k ascii, yg tidak ada akan di replace ke ?, setelah itu dikembaliin lagi ke string
    text = text.encode('ascii', 'replace').decode('ascii')
     # remove incomplete URL
    return text.replace("http://", " ").replace("https://", " ")

dflatih['kalimat']=dflatih['kalimat'].apply(remove_tweet_special)

#remove number
def remove_number(text):
    return  re.sub(r"\d+", "", text)

dflatih['kalimat']=dflatih['kalimat'].apply(remove_number)

def remove_punctuation(text):
    # Fungsi ini menghapus tanda baca dan menggantinya dengan satu spasi
    #string.punc=semua variabel di modul string yg berisi tanda baca
    #diganti dengan spasi sesuai dengan pandang tanda baca
    ganti = str.maketrans(string.punctuation, ' ' * len(string.punctuation))
    return text.translate(ganti)

dflatih['kalimat']=dflatih['kalimat'].apply(remove_punctuation)

#hapus whitespace tpi
def remove_whitespace_LT(text):
    return text.strip() #hanya awal&akhir

dflatih['kalimat']=dflatih['kalimat'].apply(remove_whitespace_LT)

# hapus karater tunggal
def remove_singl_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

dflatih['kalimat']=dflatih['kalimat'].apply(remove_singl_char)

# # hapus huruf atau apapun yg berulang2
# def reduce_repeated_characters(word):
#     return re.sub(r'(.)\1+', r'\1', word)

# dflatih['kalimat']=dflatih['kalimat'].apply(reduce_repeated_characters)

#hapus multi space, ubah ke 1 spasi
def remove_whitespace_multiple(text):
    return re.sub('\s+',' ',text) #ganti 1 spasi

dflatih['kalimat']=dflatih['kalimat'].apply(remove_whitespace_multiple)

dflatih['kalimat'].head(6)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


0    bagus sih ada beberapa bagian menu yang bukann...
1    lemotnya minta ampun bagaimana mau melayani pu...
2                                                lemot
3    mohon maaf setelah memperbarui akses menjadi l...
4                       lemot sekali kapan normal lagi
5    mau naik kereta api pesanannya makin mudah apl...
Name: kalimat, dtype: object

### TOKENISASI

In [234]:
#-------------tokenisasi-------------
#NLTK word tokenize
def word_tokenize_wrapper(text):
    return word_tokenize(text)

dflatih['kalimat_token']=dflatih['kalimat'].apply(word_tokenize_wrapper)

print(dflatih['kalimat_token'].head(10))

0    [bagus, sih, ada, beberapa, bagian, menu, yang...
1    [lemotnya, minta, ampun, bagaimana, mau, melay...
2                                              [lemot]
3    [mohon, maaf, setelah, memperbarui, akses, men...
4                 [lemot, sekali, kapan, normal, lagi]
5    [mau, naik, kereta, api, pesanannya, makin, mu...
6    [satset, banget, aplikasinya, bisa, buat, buru...
7    [tampilan, baru, memang, terlihat, segar, teta...
8    [waktu, may, bayar, sudah, tidak, memuat, teru...
9    [setelah, ditingkatkan, malah, jadi, lancar, a...
Name: kalimat_token, dtype: object


In [268]:
dflatih.to_csv('output_performa.csv', index=False)

## TF-IDF

In [235]:
from sklearn.feature_extraction.text import TfidfVectorizer

# mengubah hasil prepro ke array
dt = dflatih['kalimat_token']

vectorizer = TfidfVectorizer()
tfidf_vectors = vectorizer.fit_transform(dflatih['kalimat']) #fit_transfor untuk Learn vocabulary and idf, return document-term matrix.
tf_idf_array = tfidf_vectors.toarray()

# mendapatkan daftar kata dari proses TfidfVectorizer()
corpus = vectorizer.get_feature_names_out()

hasil_tfidf = pd.DataFrame(tf_idf_array, columns=corpus)

# menambahkan kolom kalimat yng berisi dokumen hasil prepro
hasil_tfidf.insert(0, 'Kalimat', dt)
hasil_tfidf

Kalimat  acara  acces  accesa  \
0    [bagus, sih, ada, beberapa, bagian, menu, yang...    0.0    0.0     0.0   
1    [lemotnya, minta, ampun, bagaimana, mau, melay...    0.0    0.0     0.0   
2                                              [lemot]    0.0    0.0     0.0   
3    [mohon, maaf, setelah, memperbarui, akses, men...    0.0    0.0     0.0   
4                 [lemot, sekali, kapan, normal, lagi]    0.0    0.0     0.0   
..                                                 ...    ...    ...     ...   
509  [biasanya, lambat, pol, tetapi, setelah, mempe...    0.0    0.0     0.0   
510  [mendingan, kemarin, memperbarui, malah, engga...    0.0    0.0     0.0   
511  [sekelas, aplikasi, pemerintah, jeleknya, mint...    0.0    0.0     0.0   
512  [aplikasi, kaiacces, ada, perbarui, makin, sim...    0.0    0.0     0.0   
513  [kenapa, saya, jadi, tidak, bisa, memilih, kur...    0.0    0.0     0.0   

     access  account  acess       ada  adalah  adik  ...  web  wifi  wkwk  \
0       0.0      0.0    0.0  0.208232     0.0   0.0  ...  0.0   0.0   0.0   
1       0.0      0.0    0.0  0.000000     0.0   0.0  ...  0.0   0.0   0.0   
2       0.0      0.0    0.0  0.000000     0.0   0.0  ...  0.0   0.0   0.0   
3       0.0      0.0    0.0  0.000000     0.0   0.0  ...  0.0   0.0   0.0   
4       0.0      0.0    0.0  0.000000     0.0   0.0  ...  0.0   0.0   0.0   
..      ...      ...    ...       ...     ...   ...  ...  ...   ...   ...   
509     0.0      0.0    0.0  0.000000     0.0   0.0  ...  0.0   0.0   0.0   
510     0.0      0.0    0.0  0.225254     0.0   0.0  ...  0.0   0.0   0.0   
511     0.0      0.0    0.0  0.000000     0.0   0.0  ...  0.0   0.0   0.0   
512     0.0      0.0    0.0  0.000000     0.0   0.0  ...  0.0   0.0   0.0   
513     0.0      0.0    0.0  0.000000     0.0   0.0  ...  0.0   0.0   0.0   

     woi        ya  yaitu      yang  youth  zaman  zdy  
0    0.0  0.000000    0.0  0.078124    0.0    0.0  0.0  
1    0.0  0.000000    0.0  0.000000    0.0    0.0  0.0  
2    0.0  0.000000    0.0  0.000000    0.0    0.0  0.0  
3    0.0  0.000000    0.0  0.000000    0.0    0.0  0.0  
4    0.0  0.000000    0.0  0.000000    0.0    0.0  0.0  
..   ...       ...    ...       ...    ...    ...  ...  
509  0.0  0.000000    0.0  0.000000    0.0    0.0  0.0  
510  0.0  0.000000    0.0  0.000000    0.0    0.0  0.0  
511  0.0  0.000000    0.0  0.000000    0.0    0.0  0.0  
512  0.0  0.000000    0.0  0.000000    0.0    0.0  0.0  
513  0.0  0.104045    0.0  0.123268    0.0    0.0  0.0  

[514 rows x 1258 columns]

## K-FOLD

In [264]:
dflatih = dflatih.dropna(subset=['label'])

In [275]:
dflatih = dflatih.reset_index(drop=True)

In [276]:
train_x= tf_idf_array
train_y=dflatih['label']

In [277]:
# from sklearn.model_selection import StratifiedKFold
# # from sklearn.model_selection import cross_val_score
# from sklearn.svm import SVC

# folds = StratifiedKFold(n_splits=3)

# #array score, data
# scores = []
# model = SVC(gamma='auto')

# #fungsi get score
# def get_score(model, X_train2, X_val, y_train2, y_val):
#     model.fit(X_train2, y_train2)
#     return model.score(X_val, y_val)

# #
# for train_index, val_index in folds.split(train_x, train_y):
#     # Pemilihan data untuk train dan test
#     X_train2, X_val = train_x[train_index], train_x[val_index]
#     y_train2, y_val = train_y[train_index], train_y[val_index]

#     # Menggunakan SVC dengan gamma='auto'
#     score = get_score(model, X_train2, X_val, y_train2, y_val)
#     scores.append(score)

# # Menampilkan hasil akhir
# print("Scores:", scores)

Scores: [0.5, 0.5029239766081871, 0.5029239766081871]


In [274]:
print(dflatih.index)

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            506, 507, 508, 509, 510, 511, 512, 513, 514, 515],
           dtype='int64', length=514)


## GRID SEARCH

In [285]:
train_x= tf_idf_array
train_y=dflatih['label']

In [287]:
from sklearn.model_selection import GridSearchCV
# Membuat model SVC
svm_model = SVC()

# Daftar parameter yang ingin dicoba
param_grid = {
    'kernel': ['linear', 'rbf', 'poly'],
    'C': [100, 10, 1, 0.1, 0.01],
    'gamma': [0.1, 0.01, 0.001, 1, 10],
}

# Membuat objek GridSearchCV
gridmodel = GridSearchCV(svm_model, param_grid, cv=3, return_train_score=False)

# Melakukan pencarian parameter terbaik
gridmodel.fit(train_x, train_y)

# Menampilkan hasil
# print(clf.cv_results_)


GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'gamma': [0.1, 0.01, 0.001, 1, 10],
                         'kernel': ['linear', 'rbf', 'poly']})

In [288]:
#simpan ke df
df_hasil_grid=pd.DataFrame(gridmodel.cv_results_)
df_hasil_grid[['param_kernel', 'param_C', 'param_gamma', 'mean_test_score']]

param_kernel param_C param_gamma  mean_test_score
0        linear     100         0.1         0.891020
1           rbf     100         0.1         0.892992
2          poly     100         0.1         0.501949
3        linear     100        0.01         0.891020
4           rbf     100        0.01         0.898828
..          ...     ...         ...              ...
70          rbf    0.01           1         0.501949
71         poly    0.01           1         0.501949
72       linear    0.01          10         0.501949
73          rbf    0.01          10         0.501949
74         poly    0.01          10         0.774298

[75 rows x 4 columns]

# DATA UJI

In [240]:
dfuji=pd.DataFrame()

y_test=y_test.reset_index(drop=True)

dfuji['kalimat']=X_test.flatten()
dfuji['label']=y_test
dfuji.head()

kalimat  label
0  Menurut ku nyebelin ya di saat lg promo tp ser...      0
1                                          Apk load.      0
2  Apk nya ngebantu bangettt apalagi kalo misalka...      1
3  saya rasa upgrade version yg sekarang sangat m...      1
4  KAI update otomatis di hp saya seltah saya buk...      1

## PREPROCESSING

### NORMALISASI

In [241]:
import requests

# Fungsi untuk normalisasi kata
def word_normalize(document):
    url = "https://api.prosa.ai/v2/text/normalizer"
    api_key = "eyJhbGciOiJSUzI1NiIsImtpZCI6Ik5XSTBNemRsTXprdE5tSmtNaTAwTTJZMkxXSTNaamN0T1dVMU5URmxObVF4Wm1KaSIsInR5cCI6IkpXVCJ9.eyJhcHBsaWNhdGlvbl9pZCI6Mjk2OTI3LCJsaWNlbnNlX2tleSI6IjU0MjJhODRkLWVmZGYtNDhiNC1iMDQ4LWM5N2I4OGU2MDYzMSIsInVuaXF1ZV9rZXkiOiI0YTY3YWVlMy1lMGNiLTRiMzUtOTI4Ni0xMjlhMWE2NjNkMjEiLCJwcm9kdWN0X2lkIjoxMCwiYXVkIjoiYXBpLXNlcnZpY2UiLCJzdWIiOiJkMmZmYzRhMy0wYzI2LTRjNWEtYjRiMS05NDE2NjAyMmJlMDEiLCJpc3MiOiJjb25zb2xlIiwiaWF0IjoxNzAxOTU0NjA1fQ.lJNpppK8iwSc8rH8lAPEHLxEAQW5PQGJrwYmzuAu1U0EmyZzL19dCfROqTAPViBdjecNhvPaV2wOQhJixgAgJjmtZFcdPRI0nUIxBW6AmR52fJW31bOvxcZO61zEk5LbASgBGLRs4--2yoYa3wpfDuNvV88o5slANh6GGgAADzYwnpxI4jM5quHnhNVBmzIMWNcmWOe-TF-hD6zZFX5ijGBLawFCuMjnW_dDedOJxSSPRKY_BoJLGjP-IbOkgOVuZ5F-LO1tJg_Ap7YoY4BajKSPDKuYbj56i9Wa_lj9ZlCYfybvcmbKgczHcziMm7mu9gngYfwxty5CCPquQK8wyA"  # Gantilah dengan kunci API yang diberikan kepada Anda

    # Request header
    headers = {
        "Content-Type": "application/json",
        "x-API-Key": api_key
    }

    # Request body
    payload = {
        "text": document
    }

    # request post
    response = requests.post(url, headers=headers, json=payload)

    # cek jika berhasil
    if response.status_code == 200:
        # Mengembalikan teks hasil normalisasi
        return response.json().get('normalized_text', '')
    else:
        # memberikan hasil status code dan alasan text tidak berhasil
        return response.status_code, response.text

# Menambahkan kolom baru 'text_baru' ke dfcoba sebagai kolom
dfuji['kalimat'] = dfuji['kalimat'].apply(word_normalize)

# Menampilkan DataFrame setelah penambahan kolom
print(dfuji)

                                               kalimat  label
0    Menurutku menyebalkan ya di saat lagi promo te...      0
1                                     Aplikasi memuat.      0
2    Aplikasinya membantu banget apalagi kalau misa...      1
3    saya rasa meningkatkan versi yang sekarang san...      1
4    KAI memperbarui otomatis di telepon seluler sa...      1
..                                                 ...    ...
125  Maaf untuk memperbarui terbaru malah jadi lamb...      0
126                                sataset banget woi.      1
127  Aneh. lemot. mempersulit. Jadi sulit mau pesan...      0
128                                     lancar banget.      1
129    buruk! Bukannya mempermudah, malah mempersulit!      0

[130 rows x 2 columns]


### CASE FOLDING

In [242]:
dfuji['kalimat'] = dfuji['kalimat'].str.lower()

print('Hasil case folding : \n')
print(dfuji['kalimat'].head(6))

Hasil case folding : 

0    menurutku menyebalkan ya di saat lagi promo te...
1                                     aplikasi memuat.
2    aplikasinya membantu banget apalagi kalau misa...
3    saya rasa meningkatkan versi yang sekarang san...
4    kai memperbarui otomatis di telepon seluler sa...
5    aplikasinya jadi kacau begini, mau cari nama k...
Name: kalimat, dtype: object


### CLEANING

In [245]:
dfuji = dfuji.dropna(subset=['kalimat'])

In [246]:
import string
import re #regex library
import nltk

# import word_tokenize & FreqDist from NLTK
from nltk.tokenize import word_tokenize


In [247]:
# ------ cleaning ---------
nltk.download('punkt')

# hapus tab, enter, back slice dll
def remove_tweet_special(text):
    # remove tab, baris baru, back slice
    text = text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")
    # remove non ASCII (emoticon, chinese word, .etc)//semua string di encode k ascii, yg tidak ada akan di replace ke ?, setelah itu dikembaliin lagi ke string
    text = text.encode('ascii', 'replace').decode('ascii')
     # remove incomplete URL
    return text.replace("http://", " ").replace("https://", " ")

dfuji['kalimat']=dfuji['kalimat'].apply(remove_tweet_special)

#remove number
def remove_number(text):
    return  re.sub(r"\d+", "", text)

dfuji['kalimat']=dfuji['kalimat'].apply(remove_number)

def remove_punctuation(text):
    # Fungsi ini menghapus tanda baca dan menggantinya dengan satu spasi
    #string.punc=semua variabel di modul string yg berisi tanda baca
    #diganti dengan spasi sesuai dengan pandang tanda baca
    ganti = str.maketrans(string.punctuation, ' ' * len(string.punctuation))
    return text.translate(ganti)

dfuji['kalimat']=dfuji['kalimat'].apply(remove_punctuation)

#hapus whitespace tpi
def remove_whitespace_LT(text):
    return text.strip() #hanya awal&akhir

dfuji['kalimat']=dfuji['kalimat'].apply(remove_whitespace_LT)

# hapus karater tunggal
def remove_singl_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

dfuji['kalimat']=dfuji['kalimat'].apply(remove_singl_char)

# hapus huruf atau apapun yg berulang2
def reduce_repeated_characters(word):
    return re.sub(r'(.)\1+', r'\1', word)

dfuji['kalimat']=dfuji['kalimat'].apply(reduce_repeated_characters)

#hapus multi space, ubah ke 1 spasi
def remove_whitespace_multiple(text):
    return re.sub('\s+',' ',text) #ganti 1 spasi

dfuji['kalimat']=dfuji['kalimat'].apply(remove_whitespace_multiple)

dfuji['kalimat'].head(6)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


0    menurutku menyebalkan ya di sat lagi promo tet...
1                                      aplikasi memuat
2    aplikasinya membantu banget apalagi kalau misa...
3    saya rasa meningkatkan versi yang sekarang san...
4    kai memperbarui otomatis di telepon seluler sa...
5    aplikasinya jadi kacau begini mau cari nama ko...
Name: kalimat, dtype: object

### TOKENISASI

In [248]:
#-------------tokenisasi-------------
#NLTK word tokenize
def word_tokenize_wrapper(text):
    return word_tokenize(text)

dfuji['kalimat_token']=dfuji['kalimat'].apply(word_tokenize_wrapper)

print(dfuji['kalimat_token'].head(10))

0    [menurutku, menyebalkan, ya, di, sat, lagi, pr...
1                                   [aplikasi, memuat]
2    [aplikasinya, membantu, banget, apalagi, kalau...
3    [saya, rasa, meningkatkan, versi, yang, sekara...
4    [kai, memperbarui, otomatis, di, telepon, selu...
5    [aplikasinya, jadi, kacau, begini, mau, cari, ...
6    [setelah, memperbarui, yang, terbaru, tampilan...
7    [aplikasi, bagus, banget, setelah, diperbarui,...
8    [makin, memberikan, kemudahan, pelangan, diper...
9    [bagus, dan, keren, catatan, untuk, penguna, j...
Name: kalimat_token, dtype: object


## TF-IDF

In [249]:
dfuji['kalimat']

0      menurutku menyebalkan ya di sat lagi promo tet...
1                                        aplikasi memuat
2      aplikasinya membantu banget apalagi kalau misa...
3      saya rasa meningkatkan versi yang sekarang san...
4      kai memperbarui otomatis di telepon seluler sa...
                             ...                        
125    maf untuk memperbarui terbaru malah jadi lamba...
126                                   sataset banget woi
127    aneh lemot mempersulit jadi sulit mau pesan ti...
128                                        lancar banget
129          buruk bukanya mempermudah malah mempersulit
Name: kalimat, Length: 129, dtype: object

In [250]:
# mengubah hasil pembobotan dari data biasa ke array
dt2 = dfuji['kalimat_token']

vectorizer2 = TfidfVectorizer()
tfidf_vectors2 = vectorizer.transform(dfuji['kalimat'])
tf_idf_array2 = tfidf_vectors2.toarray()

# mendapatkan daftar kata dari proses TfidfVectorizer()
corpus2 = vectorizer.get_feature_names_out()

# mengubah corpus menjadi fitur dalam pembobotan tf idf
hasil_tfidf_uji = pd.DataFrame(tf_idf_array2, columns=corpus2)

# menambahkan fitur kalimat yng berisi dokumen yang dilakukan pembobotan
hasil_tfidf_uji.insert(0, 'Kalimat', dt2)
hasil_tfidf_uji

Kalimat  acara  acces  accesa  \
0    [menurutku, menyebalkan, ya, di, sat, lagi, pr...    0.0    0.0     0.0   
1                                   [aplikasi, memuat]    0.0    0.0     0.0   
2    [aplikasinya, membantu, banget, apalagi, kalau...    0.0    0.0     0.0   
3    [saya, rasa, meningkatkan, versi, yang, sekara...    0.0    0.0     0.0   
4    [kai, memperbarui, otomatis, di, telepon, selu...    0.0    0.0     0.0   
..                                                 ...    ...    ...     ...   
124  [semenjak, pembaruan, sudah, tidak, eror, lagi...    0.0    0.0     0.0   
125  [maf, untuk, memperbarui, terbaru, malah, jadi...    0.0    0.0     0.0   
126                             [sataset, banget, woi]    0.0    0.0     0.0   
127  [aneh, lemot, mempersulit, jadi, sulit, mau, p...    0.0    0.0     0.0   
128                                   [lancar, banget]    0.0    0.0     0.0   

     access  account  acess  ada  adalah  adik  ...  web  wifi  wkwk  \
0       0.0      0.0    0.0  0.0     0.0   0.0  ...  0.0   0.0   0.0   
1       0.0      0.0    0.0  0.0     0.0   0.0  ...  0.0   0.0   0.0   
2       0.0      0.0    0.0  0.0     0.0   0.0  ...  0.0   0.0   0.0   
3       0.0      0.0    0.0  0.0     0.0   0.0  ...  0.0   0.0   0.0   
4       0.0      0.0    0.0  0.0     0.0   0.0  ...  0.0   0.0   0.0   
..      ...      ...    ...  ...     ...   ...  ...  ...   ...   ...   
124     0.0      0.0    0.0  0.0     0.0   0.0  ...  0.0   0.0   0.0   
125     0.0      0.0    0.0  0.0     0.0   0.0  ...  0.0   0.0   0.0   
126     0.0      0.0    0.0  0.0     0.0   0.0  ...  0.0   0.0   0.0   
127     0.0      0.0    0.0  0.0     0.0   0.0  ...  0.0   0.0   0.0   
128     0.0      0.0    0.0  0.0     0.0   0.0  ...  0.0   0.0   0.0   

          woi        ya  yaitu      yang  youth  zaman  zdy  
0    0.000000  0.254272    0.0  0.000000    0.0    0.0  0.0  
1    0.000000  0.000000    0.0  0.000000    0.0    0.0  0.0  
2    0.000000  0.000000    0.0  0.000000    0.0    0.0  0.0  
3    0.000000  0.000000    0.0  0.220656    0.0    0.0  0.0  
4    0.000000  0.000000    0.0  0.000000    0.0    0.0  0.0  
..        ...       ...    ...       ...    ...    ...  ...  
124  0.000000  0.000000    0.0  0.000000    0.0    0.0  0.0  
125  0.660961  0.000000    0.0  0.000000    0.0    0.0  0.0  
126  0.000000  0.000000    0.0  0.000000    0.0    0.0  0.0  
127  0.000000  0.000000    0.0  0.000000    0.0    0.0  0.0  
128  0.000000  0.000000    0.0  0.000000    0.0    0.0  0.0  

[129 rows x 1258 columns]

## PREDIKSI

In [289]:
gridmodel.best_params_

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}

In [290]:
gridmodel.best_score_

0.900777460446983

In [291]:
params=gridmodel.best_params_
model=SVC(**params)
model.fit(train_x, train_y)
y_hasil=model.predict(tf_idf_array2)

In [292]:
y_test=dfuji['label']

In [293]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix (y_test, y_hasil)

print("Classification Report:")  ##tn fp, fn tp
print(cm)

Classification Report:
[[58  7]
 [ 3 61]]


In [294]:
from sklearn.metrics import precision_score, f1_score, accuracy_score, recall_score

print ("Precision", precision_score(y_test, y_hasil))
print ("Recall",recall_score(y_test, y_hasil))
print ("F1-Score",f1_score(y_test, y_hasil))
print ("Accuracy",accuracy_score(y_test, y_hasil))


Precision 0.8970588235294118
Recall 0.953125
F1-Score 0.9242424242424244
Accuracy 0.9224806201550387


In [269]:
dfuji.to_csv('output_performa_uji.csv', index=False)

# COBA TFIDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
x_train = ["We love apples", "We really love bananas"]
tfidf_vect = vect.fit_transform(x_train)
tf_idf_arr = tfidf_vectors.toarray()
# mendapatkan daftar kata dari proses TfidfVectorizer()
term = vect.get_feature_names_out()

# mengubah corpus menjadi fitur dalam pembobotan tf idf
hasil = pd.DataFrame(tf_idf_arr, columns=term)

# menambahkan fitur kalimat yng berisi dokumen yang dilakukan pembobotan
hasil.insert(0, 'Kalimat',x_train)
hasil

Kalimat    apples   bananas      love    really        we
0          We love apples  0.704909  0.000000  0.501549  0.000000  0.501549
1  We really love bananas  0.000000  0.576152  0.409937  0.576152  0.409937

In [ ]:
x_test = ["We really love pears"]

vectorized = vect.transform(x_test)
print(vectorized.toarray())

"apple" "bananas" "love" "really" "we"

[[0.         0.         0.50154891 0.70490949 0.50154891]]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

# Data dokumen
corpus = [
    'Ini adalah dokumen pertama.',
    'Dokumen ini adalah dokumen kedua.',
    'Ini adalah dokumen ketiga.',
    'Apakah ini adalah dokumen pertama?',
]

# Langkah pertama: Membangun matriks frekuensi kata menggunakan CountVectorizer
vectorizer = CountVectorizer()
X_counts = vectorizer.fit_transform(corpus)

# Langkah kedua: Mengonversi matriks frekuensi kata menjadi matriks TF-IDF menggunakan TfidfTransformer
transformer = TfidfTransformer()
X_tfidf = transformer.fit_transform(X_counts)

# Menampilkan hasil
print("Matriks Frekuensi Kata:")
print(X_counts.toarray())
print("\nMatriks TF-IDF:")
print(X_tfidf.toarray())


Matriks Frekuensi Kata:
[[1 0 1 1 0 0 1]
 [1 0 2 1 1 0 0]
 [1 0 1 1 0 1 0]
 [1 1 1 1 0 0 1]]

Matriks TF-IDF:
[[0.43508727 0.         0.43508727 0.43508727 0.         0.
  0.657341  ]
 [0.32154224 0.         0.64308448 0.32154224 0.61616842 0.
  0.        ]
 [0.38713857 0.         0.38713857 0.38713857 0.         0.74187006
  0.        ]
 [0.3341742  0.64037493 0.3341742  0.3341742  0.         0.
  0.50487895]]
